/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b4c5ff',
        outline: '#737686',
        'surface-variant': '#dde1ff',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#efefff',
        'on-surface-variant': '#434655',
        'tertiary-container': '#5e6e85',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-tint': '#0053db',
        'surface-container-highest': '#dde1ff',
        'surface-container-high': '#e4e7ff',
        background: '#fbf8ff',
        'on-primary-container': '#eeefff',
        'on-secondary-container': '#344585',
        surface: '#fbf8ff',
        'tertiary-fixed-dim': '#b7c8e1',
        tertiary: '#46566c',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#e9f0ff',
        'on-tertiary-fixed': '#0b1c30',
        'inverse-surface': '#192b6b',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#b4c5ff',
        'surface-container-low': '#f3f2ff',
        'secondary-fixed': '#dde1ff',
        primary: '#004ac6',
        'secondary-container': '#a5b5fe',
        'primary-container': '#2563eb',
        secondary: '#4a5a9c',
        'surface-dim': '#d1d8ff',
        'on-tertiary-fixed-variant': '#38485d',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#d3e4fe',
        'outline-variant': '#c3c6d7',
        'on-primary-fixed': '#00174b',
        'surface-bright': '#fbf8ff',
        'on-surface': '#001453',
        'surface-container': '#ecedff',
        'on-background': '#001453',
        'on-secondary-fixed': '#001453',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#324283',
        'primary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b7c4ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
